version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: disabled

  - package-ecosystem: "npm"
    directory: "/js-sdk"
    schedule:
      interval: "weekly"
    rebase-strategy: disabled

  - package-ecosystem: "npm"
    directory: "/react-sdk"
    schedule:
      interval: "weekly"
    rebase-strategy: disabled

  - package-ecosystem: "npm"
    directory: "/example-app"
    schedule:
      interval: "weekly"
    rebase-strategy: disabled

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
