version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/js-sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/react-sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/example-app"
    schedule:
      interval: "weekly"
