name: Release

on:
  push:
    branches: [master]

jobs:
  release-sdk:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      HUSKY: 0 # disables husky hooks

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.*

      - name: Build
        run: make build

      - name: Release
        run: make release
        env:
          ENVIRONMENT: prod
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}

      - id: login-to-gcp
        name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: psqplt-shd-operations
          workload_identity_provider: projects/50446899764/locations/global/workloadIdentityPools/psq-github/providers/psq-github

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Release CDN
        run: make release-cdn
